# Generated by Django 4.0.5 on 2022-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_tags', models.CharField(max_length=2000, null=True)),
                ('is_discount', models.CharField(max_length=2000, null=True)),
                ('cloth_price', models.CharField(max_length=2000, null=True)),
                ('discount_price', models.CharField(max_length=2000, null=True)),
                ('image_url', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
