# Generated by Django 4.0.5 on 2022-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_alter_item_discount_price_alter_item_is_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cloth_reviews',
        ),
        migrations.AddField(
            model_name='item',
            name='cloths_tags',
            field=models.CharField(choices=[('NEW', 'NEW'), ('bestseller', 'bestseller')], max_length=2000, null=True),
        ),
    ]
